### ISSUE TITLE
getting Sentry version to my "deploy job"

### ISSUE THREAD

**Issue by tzookb** [PicturePipe/sentry-cli-orb#23]
# Feature Request

### What Is the Expected Behavior?
- I would like to get the created "sentry version"
- so I could use it in my code build code
- and then have my frontend code have the "sentry version"
- so my issues will get tracked
ie:
https://docs.sentry.io/workflow/releases/?_ga=2.229693279.2135669235.1576478068-648667344.1569404103&platform=javascript#configure-sdk

**Comment by keimlink** [comment]
Hi @tzookb,

sentry-cli has a `﻿﻿releases propose-version` subcommand.

The `sentry-cli-orb/set-version` command uses it to set the version ([source code](https://github.com/PicturePipe/sentry-cli-orb/blob/master/src/commands/%40commands.yml#L10)).

The [production deployment workflow example](https://github.com/PicturePipe/sentry-cli-orb/blob/master/src/examples/production-deployment.yml#L29) shows how to use it.

Does this allow you to set the version?

**Comment by tzookb** [comment]
Thanks Kemlink 💪🏼

already got that with my own code,
but what u mentioned seems to get the job done.

Thanks!
